<div class="box">
	<?php if($title):?>
		<div class="box-header">
			<h3 class="box-title"><?php echo $title?></h3>
			<div class="box-tools">ss</div>
		</div>
	<?php endif;?>
	<!-- /.box-header -->
	<div class="box-body">
		
		<table class="table table-bordered table-hover">
			<?php if($headers):?>
				<thead>
					<tr>
						<?php foreach($headers as $header):?>
							<th><?php echo $header;?></th>
						<?php endforeach;?>
					</tr>
				</thead>
			<?php endif;?>
			<?php if($data):?>
				<tbody>
					<?php foreach($data as $k => $v):?>
						<tr>
							<?php foreach($headers as $key => $header):?>
								<td><?php echo $v[$key];?></td>
							<?php endforeach;?>
						</tr>
					<?php endforeach;?>
				</tbody>
			<?php endif;?>
		</table>
	</div>
	<!-- /.box-body -->
	<div class="box-footer clearfix">
      <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">&raquo;</a></li>
      </ul>
    </div>
</div>


<script type="text/javascript">
	var toggleSelect = function toggleSelect(obj) {
		$('.check').attr('checked', $(obj).is(':checked'));
	}

</script>