<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?php echo $header;?>
    <small><?php echo $description;?></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

<!-- Main content -->
<section class="content"><?php echo $content;?></section>
<!-- /.content -->