<ul class="pagination pagination-sm pull-right">
	<?php if($paginator->currentPage() <= 1): ?>
		<li class="disabled"><a href="javascript:void(0);">&laquo;</a></li>
	<?php else:?>
		<li><a href="<?php echo $paginator->previousPageUrl();?>">&laquo;</a></li>
	<?php endif;?>

	<?php foreach([1, 2, 3, 4, 5, 6, 7, 8, '...', 9, 10] as $number):?>
		<?php if(is_string($number)):?>
			<li><a href="javascript:void(0);"><?php echo $number?></a></li>
		<?php else:?>
			<li><a href="<?php echo $paginator->url($number);?>"><?php echo $number?></a></li>
		<?php endif;?>
	<?php endforeach;?>

	<?php if($paginator->currentPage() >= $paginator->lastPage()): ?>
		<li class="disabled"><a href="javascript:void(0);">&raquo;</a></li>
	<?php else:?>
		<li><a href="<?php echo $paginator->nextPageUrl();?>">&raquo;</a></li>
	<?php endif;?>
</ul>